CC = gcc
CFLAGS = -Wall -g -Iinclude
LDFLAGS =
SRC_DIR = src
LIB_DIR = lib
INC_DIR = include
OBJ_DIR = obj
BIN_DIR = bin

# Nom de votre exécutable
EXEC = $(BIN_DIR)/my_program

# Trouve tous les fichiers .c dans les dossiers SRC_DIR et LIB_DIR
SOURCES = $(wildcard $(SRC_DIR)/*.c $(LIB_DIR)/*.c)

# Remplace les .c par .o pour les fichiers objet
OBJECTS = $(patsubst %.c,$(OBJ_DIR)/%.o,$(notdir $(SOURCES)))

# Règle par défaut
all: $(EXEC)

$(EXEC): $(OBJECTS) | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

# Compilation des fichiers source
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(LIB_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Création des répertoires
$(BIN_DIR) $(OBJ_DIR):
	mkdir -p $@

# Nettoyage
clean:
	$(RM) -r $(OBJ_DIR) $(BIN_DIR)

.PHONY: all clean
