all: exec
utils.o: src/lib/utils.c src/include/utils.h
	gcc -c src/lib/utils.c -o utils.o
tile.o: src/lib/tile.c src/include/tile.h
	gcc -c src/lib/tile.c -o tile.o
map.o: src/lib/map.c src/include/map.h
	gcc -c src/lib/map.c -o map.o
game.o: src/lib/game.c src/include/game.h
	gcc -c src/lib/game.c -o game.o
main.o: src/main.c src/include/game.h src/include/tile.h src/include/map.h src/include/utils.h
	gcc -c src/main.c -o main.o
exec: main.o game.o map.o tile.o utils.o
	gcc main.o game.o map.o tile.o utils.o -o exec

clean:
	rm main.o game.o map.o tile.o utils.o
	rm exec
